### ISSUE TITLE
Регистрация репозитория

### ISSUE THREAD

**Issue by FrBrGeorge** [FrBrGeorge/PythonDevelopment2023#1]
Для записи на курс надо зарегистрировать свой **публичный** git-репозиторий в виде ответа на это сообщение.

Обязательно указать:

*  ФИО (полностью)
*  Группу (и факультет, если это не ВМК)
*  URL для git clone вашего публичного репозитория, в котором планируется размещать решения Д/З

**Comment by Mathematician2000** [comment]
+ Авагян Давид Арменович
+ 524
+ https://gitlab.com/Mathematician2000/python-development-2022

**Comment by OzerovaDaria** [comment]
Озерова Дарья Александровна
321
https://github.com/OzerovaDaria/python_development2022

**Comment by kateya** [comment]
- Шастун Екатерина Алексеевна
- 528
- https://github.com/kateya/LecturesCMC-PythonDevelopment2022

**Comment by OzerovaDaria** [comment]
- Панферов Виктор Иванович
- 321
- - [https://git.cs.msu.ru/s02190692/git-prac](https://vk.com/away.php?to=https%3A%2F%2Fgit.cs.msu.ru%2Fs02190692%2Fgit-prac&cc_key=)

**Comment by KH9IZ** [comment]
- Князев Егор Иванович
- 321
- https://github.com/KH9IZ/PythonDevelopment2022

**Comment by maxporyvay** [comment]
Порывай Максим Викторович
321
https://git.cs.msu.ru/s90190054/pydev2022

**Comment by juliazadorozhnaya** [comment]
- Задорожная Юлия Андреевна
- 321
- https://github.com/juliazadorozhnaya/PythonDevelopment2022

**Comment by Prikalel** [comment]
- Поклонский Алексей Андреевич
- 319/2
- https://git.cs.msu.ru/s02190178/pythondevelopment2022

**Comment by KingAArtur** [comment]
+ Абдрахманов Артур Фаритович
+ 524
+ https://gitlab.com/AAArtur/python-app-development

**Comment by ipsavitsky** [comment]
- Савицкий Илья Павлович
- 321
- https://github.com/ipsavitsky/pythonDevelopment2022

**Comment by wianluna** [comment]
- Чистякова Анна Сергеевна
- 328
- https://github.com/wianluna/PythonDevelopment2022

**Comment by Arshehremen** [comment]
- Кабанов Андрей Вячеславович
- 625
- https://github.com/Arshehremen/pythonKabanovAV625.git

**Comment by rt2122** [comment]
- Немешаева Алиса Алексеевна
- 520
- https://github.com/rt2122/python-development

**Comment by dgreflex** [comment]
- Рубцов Владислав Евгеньевич
- 321
- [https://git.cs.msu.ru/s02190700/pythondevelopment2022](url)

**Comment by Uberariy** [comment]
- Оконишников Арий Ариевич
- 321
- https://github.com/Uberariy/pythondevelopment

**Comment by Hovushka** [comment]
- Феклисов Егор Дмитриевич
- 522
- https://github.com/Hovushka/PythonDevelopment2022

**Comment by arteeemik** [comment]
- Барышев Артем Владимирович
- 524
- https://github.com/arteeemik/PythonPractice

**Comment by KeyDiS-FBD** [comment]
- Кабиден Данияр
- 305
- https://github.com/KeyDiS-FBD/PythonDevelopment

**Comment by BondarevIvan** [comment]
Бондарев Иван Геннадьевич
507
https://github.com/BondarevIvan/python-development22

**Comment by Andrey2001** [comment]
Казаринов Андрей Вячеславович
316
https://github.com/Andrey2001/python_development_2022.git

**Comment by gregory6316** [comment]
* Нанян Георгий Артурович
* 519/2
* https://github.com/gregory6316/PythonDevelopment2022

**Comment by Drakon5999** [comment]
Лозинский Иван Павлович
519/2
https://github.com/Drakon5999/PythonDevelopment2022

**Comment by sanyavertolet** [comment]
- Фролов Александр Валерьевич
- 321
- https://github.com/sanyavertolet/PythonDevelopment2022

**Comment by gen-gematogen** [comment]
- Шутков Геннадий Алексеевич
- 321
- https://github.com/gen-gematogen/python_dev_2022

**Comment by isomov** [comment]
* Сомов Иван Сергеевич
* 617
* https://github.com/isomov/python_development_2022

**Comment by yura-leb** [comment]
Лебединский Юрий Евгеньевич
321
https://git.cs.msu.ru/s02190141/pythonprac-2022-1

**Comment by FluFFka** [comment]
Федоренко Илья Алексеевич
321
https://github.com/FluFFka/python-development-2022

**Comment by stamplevskiyd** [comment]
Стамплевский Дмитрий Максимович
321
https://github.com/stamplevskiyd/PythonDevelopment2022

**Comment by ScaryPG** [comment]
Раенчук Максим Владимирович
522
https://github.com/ScaryPG/PythonDevelopment2022

**Comment by Ushuaya** [comment]
◉ Ушаков Иван Кириллович
◉ 321 
◉ https://git.cs.msu.ru/s02190692/git-prac.git

**Comment by CocoDiorr** [comment]
Колесников Александр Николаевич
321
https://github.com/CocoDiorr/PythonDevelopment2022

**Comment by DariaSkvor** [comment]
Скворцова Дарья Владимировна
321
https://git.cs.msu.ru/s02180534/app_dev

**Comment by NastyBoget** [comment]
Богатенкова Анастасия Олеговна
528
https://github.com/NastyBoget/PythonDevelopment2022

**Comment by Veniamin-Arefev** [comment]
● Арефьев Вениамин Андреевич
● 321
● [URL для git clone вашего публичного репозитория, в котором планируется размещать решения Д/З](https://github.com/Veniamin-Arefev/PythonDevelopment2022.git)

**Comment by GirfanovOV** [comment]
- Гирфанов Олег Владимирович 
- 507
- https://github.com/GirfanovOV/python-development-2022.git

**Comment by AnyKeyShik** [comment]
- Гнилозуб-Волобуев Никита Игоревич
- 201
- https://gitlab.com/anykeyshik-msu/python-development

**Comment by weirdfishes9** [comment]
- Мушкин Илья Евгеньевич
- 518/2
- https://github.com/weirdfishes9/PythonDevelopment2022.git

**Comment by Werozel** [comment]
* Хайбулаев Глеб Сергеевич
* 525
* https://github.com/Werozel/python-vcs-2022

**Comment by Cactiw** [comment]
- Князев Андрей Александрович
- 525
- https://github.com/Cactiw/PythonDevelopment2022.git

**Comment by BinaryDancer** [comment]
- Мамаев Павел Вячеславович
- 519/2
- https://github.com/BinaryDancer/python-dev-sc

**Comment by pkorobov** [comment]
Коробов Павел Андреевич
617
https://github.com/pkorobov/python-development-2022

**Comment by DSFed8889** [comment]
- Федоров Данил Сергеевич
- 241
- https://github.com/DSFed8889/PythonDevelopment2022

**Comment by VictoriaAutMors** [comment]
Алиханов Тимур Мурадович
418
https://github.com/VictoriaAutMors/python-development-2022

**Comment by IlidanNaga** [comment]
- Корнилов Максим Алексеевич
- 517
- [https://github.com/IlidanNaga/PythonDevelopment2022](https://github.com/IlidanNaga/PythonDevelopment2022)

**Comment by Ikarona** [comment]
- Мартын Илья Орестович
- 519/2
- https://github.com/Ikarona/PythonDevelopment2022

**Comment by amateurdesperado** [comment]
- Тышова Ольга Александровна
- 617
- https://github.com/amateurdesperado/python_development_2022.git

**Comment by dovvakkin** [comment]
* Кожевников Евгений Владимирович
* 524
* https://github.com/dovvakkin/PythonDevelopment2022

**Comment by vlazarew** [comment]
- Лазарев Владимир Александрович
- 628
- https://github.com/vlazarew/PythonDevelopment2022

**Comment by TimurKinazar** [comment]
- Киназаров Темирбек Галымжанович
- 617
- https://github.com/TimurKinazar/PythonDevelopment2022

**Comment by koz1ov** [comment]
* Козлов Александр Сергеевич
* 518
* https://github.com/koz1ov/python-development-2022

**Comment by Temish09** [comment]
Биджиев Темирлан Муратбиевич
519/2
https://github.com/Temish09/python_development_2022

**Comment by ibvfteh** [comment]
Клепиков Дмитрий Витальевич 
522
https://github.com/ibvfteh/PythonDevelopment2022

**Comment by sokolcati** [comment]
- Соколова Екатерина Витальевна
- 527
- https://github.com/sokolcati/PythonDreamTeam

**Comment by WrongWizzli** [comment]
- Вартанов Дмитрий Александрович

-  420

- https://github.com/WrongWizzli/PythonDevelopment2022

**Comment by antonnikvl** [comment]
- Николаев Антон Владимирович 

- 522

- https://github.com/antonnikvl/PythonDevelopment2022

**Comment by PeterLarochkin** [comment]
Ларочкин Петр Викторович
518
https://github.com/PeterLarochkin/python2022

**Comment by MrKolbaskin** [comment]
Дубинин Владимир Дмитриевич
524
https://github.com/MrKolbaskin/msu-python-development-2022.git

**Comment by iden-alex** [comment]
Яндутов Алексей Владимирович 
524
https://github.com/iden-alex/msu-python-development-2022

**Comment by Andelme** [comment]
Даниил Малыгин Константинович
523
https://github.com/Andelme/PythonDevelopment2022

**Comment by EvgenyEmets** [comment]
Емец Евгений Сергеевич
528
https://github.com/EvgenyEmets/Python-Dev-2022.git

**Comment by WhiteFox585** [comment]
Гугучкин Егор Павлович
528
https://github.com/WhiteFox585/PySolo

**Comment by free-spearman** [comment]
- Бадекин Илья Иванович
- 327
- https://github.com/free-spearman/PythonDevelopment2022

**Comment by IlyasKharunov** [comment]
Харунов Ильяс Азатович
522
https://github.com/IlyasKharunov/python-development-2022
