### ISSUE TITLE
Запись на курс 2023

### ISSUE THREAD

**Issue by FrBrGeorge** [FrBrGeorge/PythonDevelopment2023#27]
Для записи на курс надо зарегистрировать свой **публичный** git-репозиторий в виде ответа на это сообщение.

Обязательно указать:

*  ФИО (полностью)
*  Группу (и факультет, если это не ВМК)
*  URL для git clone вашего публичного репозитория, в котором планируется размещать решения Д/З

**Comment by Zenoro** [comment]
319/1 Воронец Владимир Олегович https://gitlab.com/zenoro/coop-py-dev2023

**Comment by EvgSumina** [comment]
417 Сумина Евгения Александровна
https://github.com/EvgSumina/co-development_on_linux

**Comment by rcnegby** [comment]
417 Ступин Роман Евгеньевич
https://github.com/rcnegby/PyDev2023

**Comment by archie1602** [comment]
530 Макаров Артём Владимирович
https://git.cs.msu.ru/s02220443/python-project

**Comment by Barabanov-Nikita** [comment]
321 Барабанов Никита Сергеевич
https://github.com/Barabanov-Nikita/PythonDevelopment2023

**Comment by SmoothSwoosh** [comment]
321 Новиков Сергей Александрович
https://github.com/SmoothSwoosh/PyDev2023

**Comment by Rent4i** [comment]
313 Ильин Максим Алексеевич
https://github.com/Rent4i/Py2023

**Comment by S3RArtem** [comment]
313 Куприненко Артем Геннадьевич
https://github.com/S3RArtem/2023_Py-on

**Comment by CatherineFish** [comment]
* Чехонина Екатерина Андреевна
* 530
* https://github.com/CatherineFish/PythonDevelopment2023

**Comment by Andrew15381** [comment]
321 Чистобаев Андрей Андреевич
https://github.com/Andrew15381/Python2023

**Comment by anti-monium** [comment]
321 Голубкова Мария Сергеевна
https://github.com/anti-monium/PyDev2023.git

**Comment by mandesero** [comment]
321 Тюшев Максим Владимирович
https://github.com/mandesero/PythonDevelopment2023.git

**Comment by Lycheva02** [comment]
321 Лычева Екатерина Олеговна
https://github.com/Lycheva02/PythonDevelopment2023

**Comment by RinaRam** [comment]
530повс Мударова Рамина Мухамедовна
https://github.com/RinaRam/PythonDevelopment2023

**Comment by ViollaM** [comment]
514 Яковлева Маргарита Александровна 
https://github.com/ViollaM/python-dev-2023.git

**Comment by NatalkaPron** [comment]
Пронина Наталия Михайловна
417
https://github.com/NatalkaPron/app-develop.git

**Comment by Some-Air** [comment]
- Башкатова Ольга Сергеевна
- 221м, философский факультет
- https://github.com/Some-Air/whats_it.git

**Comment by Pusenkas** [comment]
321 Иванов Павел Игоревич
https://git.cs.msu.ru/s02200645/pydev2023

**Comment by max200018** [comment]
519/2 Архипов Максим Дмитриевич
https://github.com/max200018/PythonDevelopment2023

**Comment by nmashanik** [comment]
514 Никитина Мария Алексеевна
https://github.com/nmashanik/python-development-2023.git

**Comment by makundr** [comment]
316 Андрианов Владислав Дмитриевич
https://github.com/makundr/PyDevelopment

**Comment by koralexa** [comment]
528 Корабулина Александра Сергеевна
https://github.com/koralexa/python_coop_dev_2023.git

**Comment by temnoosh** [comment]
517 Ушакова Анна Евгеньевна
https://github.com/temnoosh/PyDev2023

**Comment by amoraleo** [comment]
519/2 Морозов Леонид Алексеевич
https://gitlab.com/amoraleo/python_codevelopment

**Comment by s-ed-s** [comment]
519/2 Сабиров Эдуард Радикович
https://gitlab.com/sabedo/python-development2023

**Comment by Atmptdie** [comment]
316 Хорошев Олег Евгеньевич
https://github.com/Atmptdie/PyDev2023

**Comment by TheFieryLynx** [comment]
528 Бирюков Андрей Матвеевич
https://github.com/TheFieryLynx/PythonDevelopment2023

**Comment by AlexanderYakovenko1** [comment]
622 Яковенко Александр Викторович
https://github.com/AlexanderYakovenko1/PythonDevelopment2023

**Comment by CrustaceanJ** [comment]
517 Швец Павел Игоревич
https://github.com/CrustaceanJ/PyDev2023

**Comment by NotSlacker** [comment]
530 Идрисов Ибрагим Эскирханович
https://github.com/NotSlacker/python-development-course

**Comment by DenisRogozhin** [comment]
525 Рогожин Денис Андреевич
https://github.com/DenisRogozhin/PythonDevelopment2023

**Comment by EvgenijGod** [comment]
517 Косарев Евгений Александрович
https://github.com/EvgenijGod/python_dev_msu_course

**Comment by SamburskyAlexander** [comment]
517 Самбурский Александр Ильич
https://github.com/SamburskyAlexander/PythonDevelopment2023

**Comment by JohannBlood** [comment]
321 Путилов Георгий Константинович
https://github.com/JohannBlood/Joint.git

**Comment by mexMat** [comment]
608 Филиппов Андрей Александрович
https://github.com/mexMat/23-02-python-dev-special

**Comment by PeterChizhov** [comment]
608 Чижов Пётр Сергеевич
https://github.com/PeterChizhov/python_teamdev

**Comment by kotopesutility** [comment]
521 Загайнов Данила Кириллович
https://git.cs.msu.ru/s02170613/pydev23

**Comment by YegorCrazy** [comment]
321 Бритенков Егор Сергеевич
https://github.com/YegorCrazy/PythonDevelopment2023.git

**Comment by MeshchaninovViacheslav** [comment]
517 Мещанинов Вячеслав Павлович
https://github.com/MeshchaninovViacheslav/PythonDevelopment2023

**Comment by RomanPupkin** [comment]
608 Фазлетдинов Рамиль Рустамович
https://github.com/RomanPupkin/PythonDevelopment2023

**Comment by miron6** [comment]
519/2 Миронов Денис Дмитриевич
https://github.com/miron6/PythonDevelopment2023.git

**Comment by FoggyX** [comment]
519/2 Назаров Дмитрий Ильич
https://github.com/FoggyX/PythonDevelopment2023.git

**Comment by kholex** [comment]
617 Холодов Александр Валерьевич
https://github.com/kholex/PythonDevelopment2023

**Comment by bogdann29** [comment]
321 Пуртов Богдан Сергеевич
https://github.com/bogdann29/PythonDev.git

**Comment by makler322** [comment]
524 Воронцов Александр Алексеевич
https://github.com/makler322/PythonDevelopment2023

**Comment by IgorYashch** [comment]
321 Ященко Игорь Сергеевич
https://github.com/IgorYashch/PythonDevelopment.git

**Comment by hgfs113** [comment]
517 Попов Дмитрий Николаевич
https://github.com/hgfs113/coop-dev-prac23

**Comment by lexabr** [comment]
524 Зубарёв Алексей Витальевич
https://github.com/lexabr/PythonDevelopment2023

**Comment by mr-volch** [comment]
321 Волчанинов Алексей Павлович
https://git.cs.msu.ru/s02200541/prak_repo

**Comment by bulatral42** [comment]
503, Валиахметов Булат Ильдарович
https://github.com/bulatral42/python-collab-msu.git

**Comment by GGEasyGG** [comment]
608 Павлишин Кирилл Юрьевич
https://github.com/GGEasyGG/PythonDevelopment2023

**Comment by AndreyAkifyev** [comment]
420 Акифьев Андрей Владимирович
https://github.com/AndreyAkifyev/pydev2023

**Comment by sssqweeeed** [comment]
420 Воронин Михаил Яковлевич
https://github.com/sssqweeeed/pydev2023

**Comment by Filenko** [comment]
321 Филенко Тимофей Олегович
https://github.com/Filenko/PythonDevelopment2023

**Comment by MorozovMax** [comment]
508 Морозов Максим Гаррьевич
https://github.com/MorozovMax/Python-joint-development.git

**Comment by RefalMaster** [comment]
517 Бикметов Данил Наильевич
https://gitlab.kaizen.yandex-team.ru/bicdan22/PythonDevelopment2023

**Comment by Aklin936** [comment]
Ненахов Нил Денисович
305 гр
https://github.com/Aklin936/python-development-2023

**Comment by NikaMorozova** [comment]
Морозова Вероника Геннадьевна
321 группа
https://gitlab.com/venticinque/pythondevelopment2023

**Comment by naya451** [comment]
Белова Анастасия Алексеевна
328 группа
https://github.com/naya451/MSU-speccourse

**Comment by kr3go6** [comment]
324 Кривов Егор Иванович
https://github.com/kr3go6/PythonDevelopment2023

**Comment by dianarudenko** [comment]
528 Руденко Диана Алексеевна
https://github.com/dianarudenko/python_dev_2023

**Comment by iemttt** [comment]
619-1 Мокеев Иван Евгеньевич
https://github.com/iemttt/PythonDev23

**Comment by VeryLittleAnna** [comment]
Гриненко Анна Андреевна
320 группа
https://github.com/VeryLittleAnna/PythonDevelopment2023

**Comment by Idermonia** [comment]
Епифанова Агата Станиславовна
320 группа
https://github.com/Idermonia/Python_dev_2023.git

**Comment by P34K1N** [comment]
Федоров Владислав Владимирович
123ски_скс
https://github.com/P34K1N/python_uneex_2023

**Comment by Sidl419** [comment]
517 Сидоров Леонид Станиславович
https://github.com/Sidl419/PythonDev2023

**Comment by Magic-Rabbit** [comment]
327 Шабанов Валентин Дмитриевич
https://github.com/Magic-Rabbit/pythondev2023

**Comment by anastasialiniaeva** [comment]
619-1 Линяева Анастасия Игоревна
https://gitlab.com/krause.anastasiy/pydev2023

**Comment by hexangel1** [comment]
Артамонов Георгий Игоревич
514 группа
https://github.com/hexangel1/PythonDevelopment2023

**Comment by EgorKrivotulov** [comment]
305 Кривотулов Егор Владимирович
https://github.com/EgorKrivotulov/Python-collaborative-application-development

**Comment by PetrovTimur** [comment]
305 Петров Тимур Павлович
https://github.com/PetrovTimur/PythonDevelopment2023

**Comment by se4en** [comment]
528 Мотриченко Дмитрий Олегович
https://github.com/se4en/msu_python_development_2023

**Comment by Sbdjaro** [comment]
320 Тэаро Кирилл Алексеевич
https://github.com/Sbdjaro/PythonDevelopment2023

**Comment by DenChess3** [comment]
316 Рачков Денис Сергеевич
https://github.com/DenChess3/PythonGit

**Comment by alexey-kaz** [comment]
421 Казантаев Алексей Дмитриевич
https://github.com/alexey-kaz/PyDev2023

**Comment by levkiss** [comment]
608 Кислюк Лев Сергеевич
https://github.com/levkiss/PythonDevelopment2023

**Comment by k-berber** [comment]
517 Бербер Кирилл Андреевич
https://github.com/k-berber/python_development

**Comment by iluha-grig** [comment]
517 Григорьев Илья Андреевич
https://github.com/iluha-grig/Python-development

**Comment by SannTim** [comment]
321 Санников Тимофей Владимирович
https://git.cs.msu.ru/s02210318/python-dev

**Comment by karlstedt020** [comment]
321 Карлстедт Антон Стефанович

**Comment by murlinmurlo** [comment]
321 Бурдюгова Мария Витальевна
https://github.com/murlinmurlo/pythondev
